services:
  web:
    build: .
    container_name: retrievvy
    ports:
      - "7300:7300"
    environment:
      QDRANT_URL: http://qdrant:6333
      WEB_HOST: 0.0.0.0
      WEB_PORT: 7300
      WEB_TOKEN: ${WEB_TOKEN:-}
      DEBUG: ${DEBUG:-false}
    volumes:
      - ./storage/retrievvy_data:/app/data
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.13.5
    container_name: retrievvy_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./storage/qdrant_storage:/qdrant/storage